<a href='http://www.algebra.hr'> <img src='../algebra_logo_color_h.png' alt="Algebra" width="500" /></a>
___
# NumPy - Numerical Python

NumPy – Numerical Python neizostavni je paket za numeričke proračune u Pythonu. Alat naziva Matlab koristi se za tehničke proračune, kao na primjer proračun opterećenja čelične konstrukcije mosta ili toplinskog naprezanja u bloku motora tijekom rada i sl. Kako su povezani Python i alat Matlab? Matlab je snažan alat, ali u njemu nije tako jednostavno pisati kôd. Bilo bi odlično kada bismo imali snagu Matlaba, a jednostavnost Pythona. Tako dolazimo do seta biblioteka (skupina klasa i metoda određenih funkcionalnosti) koji koriste Python i koji su alternativa Matlabu.

U tom setu temelj je NumPy. Namijenjen je za numeričke proračune. Zatim je ovdje SciPy (*Scientific Python*) razvijen na temeljima NumPy biblioteke i nudi veliki izbor gotovih algoritama za razne znanstvene proračune. Tu je i Pandas, također razvijen na temeljima NumPy biblioteke, koji služi za obradu podataka u obliku tablice. Matplotlib biblioteka koristi NumPy kao temelj, a služi za vizualizaciju podataka.

Pandas i matplotlib smo već upoznali. Upoznajmo se s njihovom temeljnom bibliotekom NumPy.

NumPy je *open-source* biblioteka namijenjena za kompleksne matematičke proračune. Nudi jako puno matematičkih funkcija, generator je nasumičnih brojeva, podrška je za proračune vezane uz linearnu algebru, Fourierove transformacije. Mi ćemo ga koristiti za obradu višedimenzionalnih nizova i matrica.

Na službenoj stranici NumPy biblioteke možete pronaći dokumentaciju, preuzeti i instalirati NumPy, pronaći neke tečajeve, pridružiti se zajednici korisnika. Poveznica na stranicu je: https://numpy.org/.

## NumPy primjena

Već smo spomenuli da se NumPy najčešće koristi za znanstvene matematičke proračune, ali tu nije kraj primjeni NumPy paketa. Intenzivno se koristi i za statističke proračune, matematičke operacije nad matricama, kopiranje i pregled nizova, linearnu algebru, pretraživanje, sortiranje i prebrojavanje elemenata nizova i matrica.

# ndarray objekt - temelj NumPy biblioteke

Temelj NumPy biblioteke je *ndarray* objekt. Naziv dolazi od *n-dimensional array*, odnosno višedimenzionalni niz. Prije nego pojasnimo što su višedimenzionalni nizovi, dobro bi bilo objasniti što je to niz, odnosno *array*. *Array* je tip podatka koji je najsličniji Python listi. Nije isti jer postoje razlike, ne samo u načinu kako je niz programiran za rad s podacima (što je tema za kolegije na fakultetima), nego i nekoliko je nama "vidljivih" razlika. *Array* (mi ćemo dalje u tekstu ponekad koristiti i naziv *Array*):
- je kolekcija elemenata istog tipa podataka
- podržava izravne matematičke operacije nad elementima (*array* * 2 - množi svaki element niza s brojem dva)
- nije zamišljen za mijenjanje elemenata. podržava ih, ali je daleko manje učinkovit od liste.

Najbolje je napraviti nekoliko primjera pa će zasigurno biti jasnije.

Kao i uvijek do sada, prvo moramo napraviti *import* NumPy biblioteke kako bismo kasnije mogli koristiti dostupne mogućnosti.

Preporuka je koristiti način uključivanja biblioteke koji je gotovo postao standard. Uporaba drugačijeg načina neće utjecati na funkcionalnost programa, ali neće biti u skladu s najboljim praksama.

In [1]:
import numpy as np

In [2]:
python_lista = [1, 2, 3, 4, 5]
np_array = np.array([1, 2, 3, 4, 5])

print(f'Mnozenje python liste {python_lista * 2}')
print(f'Mnozenje NumPy matrice {np_array * 2}')

Mnozenje python liste [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Mnozenje NumPy matrice [ 2  4  6  8 10]


Ali pomoću NumPy biblioteke Python listu, možemo pretvoriti u ndarray i pomnožiti svaki element s, recimo tri, jako jednostavno.

In [3]:
np.multiply(python_lista, 3)

array([ 3,  6,  9, 12, 15])

**PITANJE<br>
U kojoj situaciji metoda *multiply* neće raditi, odnosno javit će grešku?<br>
Pokažite na primjeru.**

In [4]:
python_lista = [1, 2, 3, 'Algebra', 'Python', 4, 5, 3.1415, False]
np.multiply(python_lista, 3)

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U32'), dtype('int32')) -> None

Nastavimo dalje s istraživanjem osnovnih mogućnosti *ndarray* tipa podataka.

### *ndarray size* - broj elemenata u *Array* objektu

Svojstvo *size* vraća ukupan broj elemenata u objektu. Pokažimo to na primjeru.

In [7]:
podaci = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(podaci)
np_podaci = np.array(podaci)
print(np_podaci)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


Uočite kako je ispis podataka drugačiji.

Provjerimo koliko elemenata ima novokreirani *Array* objekt:

In [8]:
np_podaci.size

9

Vidjeli smo kako je ispis za *Array* drugačiji od obične Python liste. Svaku listu je prikazao u novom redu. Na ovaj način smo dobili 3x3 matricu.

Ako zamislimo da je NumPy *Array* u koordinatnom sustavu, svaki od redova bit će na X osima, svaka kolona će biti na Y osi. Ovaj podatak zovemo dimenzije, odnosno osi ili engleski *axis*. Jako često ćemo trebati informaciju koliko dimenzija ima naš *Array* objekt. Za to koristimo svojstvo ***ndim***. Provjerimo koliko naš *Array* objekt ima osi:

In [10]:
np_podaci.ndim

2

Očekivano, dvije osi. Kako izgleda *Array* s tri osi?

In [29]:
lista = [[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
        [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]],
        [[25, 26, 27, 28], [29, 30, 31, 32], [33, 34, 35, 36]]]

tri_d = np.array(lista)
tri_d

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [16]:
tri_d.ndim

3

Dakle, treću dimenziju ćemo dobiti ukoliko *Array* kreiramo od liste, koja kao elemente ima listu, koja opet kao elemente ima listu.

A kakvog je oblika naš *Array*? Ako koristimo svojstvo *Shape*, dobit ćemo *tuple* s brojem redova i stupaca koje imamo, ali po svakoj dimenziji. Najbolje je to pokazati na primjeru kako bi vam bilo jasnije.

In [17]:
np_podaci.shape

(3, 3)

Vidimo da se naš *Array np_podaci* sastoji od dvije dimenzije (imamo samo dva podatka u *tupleu*) u kojima imamo tri reda i tri stupca. Provjerimo kakvog je oblika *Array tri_d*:

In [18]:
tri_d.shape

(3, 3, 4)

Sada smo dobili tri podatka pa je zaključak kako imamo **tri** dimenzije i u svakoj od dimenzija imamo **tri reda** i **četiri stupca**.

Već smo rekli kako u *Array* možemo pohraniti podatke **istog tipa**, ali to ne znači da ti podaci moraju biti isključivo cijeli brojevi. Osim toga, *Array* je namijenjen za rad s velikom količinom podatka pa je podataka o tipu i količini memorije koju taj tip zauzima jako koristan. Provjerimo koji je tip (*dtype*) u našim *Array* objektima te koliko memorije oni zauzimaju pojedinačno (*itemsize*), odnosno ukupno (*nbytes*).

In [19]:
print(np_podaci.nbytes)
print(np_podaci.itemsize)
print(np_podaci.dtype)

print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

36
4
int32
144
4
int32


Vidimo da oba *Array* objekta imaju isti tip (*int64*). To možemo definirati tijekom kreiranja *Array* objekta tako da metodi *array* proslijedimo argument *dtype* s nazivom tipa podataka. Probajmo umjesto cijelih brojeva koristiti decimalne.

In [30]:
tri_d = np.array(tri_d, dtype=np.float64)
tri_d

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]],

       [[25., 26., 27., 28.],
        [29., 30., 31., 32.],
        [33., 34., 35., 36.]]])

Provjerimo sada tip i količinu memorije za *Array tri_d*.

In [21]:
print(tri_d.nbytes)
print(tri_d.itemsize)
print(tri_d.dtype)

288
8
float64


Tip je sada drugačiji, a količina memorije je ostala ista jer *int64* i *float64* zauzimaju isto memorije (*8 byte*).

### Reshape

*Reshape* je metoda pomoću koje možemo promijeniti oblik, odnosno *shape* našeg *Array* objekta. Pokažimo to na primjeru. *Reshape* metoda prima *tuple* kao argument, ali umnožak njegovih elemenata mora biti isti kao i umnožak inicijalnih vrijednosti *Array* objekta. To znači da smo mi imali *tuple* (3, 3, 4) kao rezultat, a umnožak tih brojeva je 36. To znači da umnožak elemenata novog oblika mora biti 36. Recimo, (9, 4).

In [31]:
print(f'Shape tri_d prije: \t{tri_d.shape}')
print(f'tri_d prije: \n{tri_d}')

tri_d = tri_d.reshape(9, 4)

print(f'Shape tri_d poslije: \t{tri_d.shape}')
print(f'tri_d poslije: \n{tri_d}')

Shape tri_d prije: 	(3, 3, 4)
tri_d prije: 
[[[ 1.  2.  3.  4.]
  [ 5.  6.  7.  8.]
  [ 9. 10. 11. 12.]]

 [[13. 14. 15. 16.]
  [17. 18. 19. 20.]
  [21. 22. 23. 24.]]

 [[25. 26. 27. 28.]
  [29. 30. 31. 32.]
  [33. 34. 35. 36.]]]
Shape tri_d poslije: 	(9, 4)
tri_d poslije: 
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]
 [17. 18. 19. 20.]
 [21. 22. 23. 24.]
 [25. 26. 27. 28.]
 [29. 30. 31. 32.]
 [33. 34. 35. 36.]]


Izgubili smo jednu dimenziju. Svedimo *tri_d Array* na samo jednu dimenziju.

In [34]:
tri_d = tri_d.reshape(36)
tri_d

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36.])

Dakle, lista je jednodimenzionalni niz.

### Generator nasumičnih brojeva

Do sada smo vidjeli kako NumPy *ndarray* možemo kreirati iz neke Python liste ili izravno pomoću *ndarray()* metode. Međutim, NumPy nudi nekoliko načina za kreiranje *Array* objekata od nasumično kreiranih objekata koje možemo koristiti u našim matematičkim analizama.

Krenimo s generatorom *Arraya* objekta u kojem su sve nule, tako što ćemo koristiti metodu *zeros()*, kojoj ćemo kao argument predati *tuple* s definiranim oblikom (*shape*) željenog *Array* objekta.

In [41]:
nule = np.zeros((3, 4, 4))
nule

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Ako imamo metodu *zeros()*, moguće je da postoji identična metoda za jedinice naziva *ones()*. Provjerimo, ali pokušajmo promijeniti tip podatka u cijele brojeve (*dtype*).

In [42]:
jedinice = np.ones((3, 4, 4))
jedinice

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

Odlično. Ipak, bilo bi daleko korisnije kada bismo mogli imati *Array* s predefiniranom vrijednošću, kao recimo 3.14. Već smo vidjeli da *Array* objekt možemo množiti pa pokušajmo to iskoristiti.

In [43]:
nd_pi = 3.1415 * jedinice
nd_pi

array([[[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]],

       [[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]],

       [[3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415],
        [3.1415, 3.1415, 3.1415, 3.1415]]])

Dakle, morali smo prvo kreirati *Array* željenog oblika s jedinicama i onda ga pomnožiti sa željenom vrijednošću. Postoji  brži i učinkovitiji način. Metoda *full()* koja prima dva argumenta, jedan tuple s oblikom *Arraay* objekta, a drugi s brojem koji želimo imati u našem *Array* objektu.

In [45]:
np_pi = np.full((3, 4, 4), 7)
np_pi

array([[[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]],

       [[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]])

Ponekad želimo imati *Array* u kojem su elementi poredani u sekvencu. Sjećate li se metode *range(start, stop, korak)*? NumPy radi s nizovima (*Arrays*) pa bi onda umjesto *array_range* trebala biti metoda naziva *arange*. Ostalo bi trebalo biti isto. Provjerimo.

In [48]:
np_arange = np.arange(5, 15)
np_arange = np.arange(5, 15, 3)
np_arange

array([ 5,  8, 11, 14])

Pomoću *arange()* metode generiramo jednodimenzionalni niz koji ima definiranu početnu vrijednost, krajnju (koja nije uključena) i korak između njih. NumPy nam omogućava kreiranje *Array* objekta koji ima početnu i krajnju vrijednost te broj elemenata između njih. Ova metoda zove se *linspace()*. Isprobajmo ju.

In [51]:
np_linspace = np.linspace(5, 15, 3)
np_linspace

array([ 5., 10., 15.])

In [52]:
np_linspace = np.linspace(5, 15, 5)
np_linspace

array([ 5. ,  7.5, 10. , 12.5, 15. ])

*arange* i *linspace* metode generiraju jednodimenzionalno polje.

**ZADATAK<br>
Generirajte nekoliko novih *Array* objekata pomoću *arange* i *linspace* metoda (neka ih bude minimalno 4) te im promijenite oblik po izboru.**

NumPy ima i generator nasumičnih brojeva unutar normalne distribucije (nula je sredina svih generiranih brojeva na ovaj način - brojevi se generiraju u pozitivnom i negativnom smjeru). Iskoristimo ga.

Korisno. Ako nam je ovaj niz ipak nedovoljan, možemo ga jednostavno ponoviti onoliko puta koliko nam je potrebno. Za ponavljanje ćemo ipak koristiti čitljiviji niz kako bismo jednostavnije uočili obrasce ponavljanja.

Svakako napravite ponavljanje i s nasumično generiranim brojevima.

### *Slice* notacija

**ZADATAK<br>
Ako smo do sada mogli koristiti neke metode i funkcije vezane uz Python liste, provjerite možete li koristiti slice notaciju nad NumPy *Array* objektom. Podsjetnik: lista\[prvi_element : zadnji_element : korak\]. Sjetite se što znači negativni predznak za korak ili ako izostavite jedan od elemenata kao npr \[ : : \].**

Vjerujem da ste uspjeli jer se radi o jednodimenzionalnim nizovima. Međutim, kada radimo s višedimenzionalnim nizovima i ako koristimo *slice* notaciju, onda trebamo navesti i os na koju želimo primijeniti notaciju. Probajmo to napraviti s našim *tri_d Array* objektom.

Pokušajmo dohvatiti sve elemente od početnog, do elementa s indeksom 4 (nije uključen).

Kao rezultat smo dobili prva četiri reda. Dakle, redove s indeksima 0, 1, 2 i 3. Što ako želimo dohvatiti prva četiri elementa drugog reda? Ako ponovimo gornju naredbu, onda ćemo dobiti sve iz prva četiri reda, a mi želimo samo neke elemente iz drugog reda.

NumPy ima rješenje i za to. U *slice* notaciji ćemo dodati još jedan argument na prvo mjesto koji će odrediti o kojem redu se radi, a nakon tog argumenta ćemo navesti koje elemente tog reda želimo.

Pokušajmo onda iskoristiti ovu notaciju da dohvatimo zadnja 4 elementa predzadnjeg reda.

Vidjeli smo da je rad s redovima predefiniran. To znači kako nismo morali definirati o kojem se redu radi, nego je NumPy sam pretpostavio da želimo dohvatiti podatke iz redova. Međutim, što ako želimo dohvatiti podatke iz stupaca? Recimo, koji su podaci u drugom stupcu *tri_d* niza?

Odgovor na ovo pitanje je jako sličan odgovoru za redove, samo što argument koji navodimo za broj stupca, navodimo poslije *slice* notacije. Pokažimo na primjeru pa će biti jasnije:

Koja je vrijednost u zadnja četiri elementa četvrtog stupca?

Dakle, *slice* notacija vrijedi i za NumPy nizove. Jednodimenzionalni nizovi su u stvari liste, kao što smo to naučili ranije, a ako želimo raditi s dvodimenzionalnim nizovima, onda slice notacija ima dodatne argumente. Prvi argument je indeks reda, nakon kojeg filtriramo pomoću *slice* notacije željene elemente. Ako želimo raditi sa stupcima, onda prvo navodimo *slice* notacijom filter elemenata, a nakon toga argument s indeksom stupca. Argumenti se, kao i kod funkcija, odvajaju zarezom.

Što ako želimo dohvatiti više redaka ili više stupaca? Ovdje ćemo morati koristiti dvostruku *slice* notaciju, odnosno kao da imamo dva argumenta. Prvi argument je zapisan u *slice* notaciji i odnosi se na redove, a drugi, također zapisan u *slice* notaciji, odnosi se na stupce. Zamislite kao da smo mišem selektirali dio tabele u Excel tabeli. Najbolje da to pokažemo na primjeru, u kojem ćemo dohvatiti prva četiri reda i zadnja četiri elementa tih prvih četiriju elementa.

**ZADATAK<br>
Kreirajte niz od 64 elemenata (početni i krajnji elementi neka budu proizvoljni). Prilagodite oblik niza tako da niz bude dvodimenzionalan.**

**Dohvatite samo PRVI RED, samo ZADNJI RED, samo PRVI STUPAC, samo ZADNJI STUPAC. Dohvatite centralne elemente niza (najmanja tabela u sredini niza).**

**Pokušajte sve to napraviti s trodimenzionalnim nizom. Koje zaključke ste donijeli?**

**Pomoć za *slice* notaciju**

<img src='./array-slice.png' alt="Array slice notacija" />

### Kreiranje niza pomoću funkcije

Prije nego krenemo dalje s jednostavnijim matematičkim operacijama, upoznajmo se s još jednom opcijom za kreiranje nizova. Niz možemo kreirati pomoću rezultata neke funkcije. Ovo nam može biti jako korisno.

Na primjer: imamo dva broja koje želimo transformirati tako da drugi broj pomnožimo s brojem 15 i to dodamo prvom broju. Rezultat ove funkcije ćemo iskoristiti kao ulazni parametar za kreiranje niza. Za to će nam koristiti metoda *fromfunction* koja kao prvi argument prima funkciju (dakle, koristimo *lambda* funkcije), drugi element je oblik, odnosno *tuple* s podacima za *shape* niza i treći opcionalni argument je tip podatka. Pokažimo na primjeru.

**PITANJE<br>
Objasnite, kako je moguće da funkcija vrati neki rezultat, ako u funkciju nismo proslijedili nikakve argumente?**

U funkciju smo indirektno proslijedili argumente na osnovu našeg *tuple* objekta koji definira oblik niza. Dakle, metoda *fromfunction* radi tako da poziva funkciju onoliko puta koliko niz ima elemenata na osnovu definiranog oblika. U našem slučaju to je 40. Prvi poziv funkcije je s argumentima funkcija (0, 0), drugi poziv je funkcija ( 0, 1), a zadnji poziv je funkcija (4, 7).

**Zadatak<br>
Prikažite tablicu množenja do 12 pomoću NumPy niza i funkcije.**

## Kopiranje cijelog ili dijela niza

Sada smo naučili kako izdvojiti dio niza iz veće cjeline. Ako taj dio pohranimo u neku varijablu i dalje ćemo imati **referencu** na originalne podatke. Pokažimo to na primjeru tablice množenja:

Kao što vidimo, promijenili smo **originalni skup podataka**. To treba izbjegavati, treba raditi na kopiji podataka. Za to imamo metodu *copy()*. Iskoristimo to na istom primjeru tablice množenja:

### Povezivanje nizova

Osim što niz možemo kopirati pa tako kreirati novi niz, novi niz možemo kreirati i spajanjem dvaju ili više nizova u jedan pomoću *concatenate, vstack* i *hstack* metoda. Pokažimo to na primjeru.

Možemo umjesto definiranja osi (*axis argument*) koristiti *vstack* (vertikalni smjer) ili *hstack* (horizontalni smjer)

### Razdvajanje nizova

Znamo kako izdvojiti dio niza u jednu novu zasebnu cjelinu, ali ponekad imamo potrebu niz podijeliti na više cjelina, odnosno nizova po nekom kriteriju. Za to koristimo metode *split, hsplit* i *vsplit*. Pokažimo na primjerima kako se koriste ove metode.

Kao argument, na koliko dijelova možemo proslijediti jednodimenzionalni niz pa ćemo prvotni niz podijeliti na više različitih dijelova. Recimo, prvo ćemo izdvojiti prva tri stupca, zatim preostale elemente u novi niz sve do 6. stupca. Kako nemamo toliko, dobit ćemo i jedan prazan niz.

Ako svaki novi dio pohranimo u neku novu varijablu, dobit ćemo nove *poglede* na originalni niz (sjetite se, nema kopiranja, nego i dalje zadržavamo reference pa ovo možemo smatrati kao pogled / *view* na taj dio niza.).

**Vježba<br>
Napravite nove kopije nizova.**

Ovo ćemo najlakše pojasniti na nekom većem nizu.

## Matematičke operacije s nizovima

NumPy je nastao kako bismo brzo i jednostavno izvršavali kompleksne matematičke operacije nad velikom količinom podatka. Da bismo došli do kompleksnih matematičkih operacija, krenut ćemo s jednostavnijim kao što su osnovne matematičke operacije:
- zbrajanje i oduzimanje
- množenje i dijeljenje
- potencije.

Ili pomoću funkcije metode *add()*:

Analogno prethodnom primjeru, oduzimanje bi bilo pomoću znaka - ili metode *subtract()*.

**PITANJE <br>
Zbog čega smo kao rezultat oduzimanja dobili sve iste brojeve?**

Odgovor: zato jer je razlika elemenata po pozicijama uvijek identična. Da smo kreirali drugačije nizove, razlika bi bila drugačija.

**Primjere za množenje i dijeljenje, pokušajte napraviti sami.<br>
**Pomoć: koristite engleske nazive za množenje i dijeljenje, odnosno *multiply* i *divide.***

### Ugrađene matematičke funkcije u NumPy biblioteci

NumPy ima jako puno ugrađenih funkcija. Da nabrojimo samo neke:
- trigonometrijske funkcije: *sin(), cos()* i *tan()*
- funkcije za korjenovanje *sqrt()* te *exp()* funkciju za računanje potencija nekog broja
- *log(), log2()* i *log10()* za računanje logaritama s bazom *e*, 2 ili 10
- *round()* za zaokruživanje na određeni broj decimalnih mjesta.

**Generirajte niz s nasumičnim brojevima proizvoljnog oblika (minimalno 4,4) te nad tim nizom provjerite kako rade navedene funkcije.**

### Statističke operacije u NumPy biblioteci
- *np.mean* - prosjek svih vrijednosti u nizu
- *np.std* - standardna devijacija
- *np.sum* - suma svih elemenata, metoda koristi argument *axis*
- *np.prod* - produkt svih elemenata
- *np.min, np.max* - minimalna/maksimalna vrijednost u nizu
- *np.argmin, np.argmax* - indeks elementa koji ima minimalnu/maksimalnu vrijednost
- *np.all* - vraća True ako su svi elementi nonzero (elementi koji imaju vrijednost nula ili nemaju definiranu vrijednost)
- *np.any* - vraća True ako je bilo koji element *nonzero*

Generirajmo niz nasumičnih brojeva i provjerimo neke od gore navedenih statističkih operacija.

**Vježba<br>
Dovršite primjere za preostale statističke funkcije tako da za svaku kreirate novi niz.**

### Funkcije filtriranja

NumPy ima ugrađenih nekoliko funkcija za filtriranje i obradu vrijednosti elementa u nizovima.
Prva s kojom ćemo se upoznati je *where()*. Ova funkcija prima prvi argument kao uvjet za filtriranje, a druga dva su operacije nad vrijednostima elemenata niza. Ako je rezultat uvjeta iz prvog argumenta točan, onda se primjenjuje drugi argument, a ako nije točan, onda se primjenjuje treći argument.

Generirajmo niz od 9 elemenata od -4 do +4 i svaki element koji je manji od nula podignimo na kvadrat, a ako je veći od nula, podignimo na treću potenciju.

Druga jako slična funkcija je *select()*. Ova funkcija prima listu uvjeta kao prvi argument i listu operacija nad elementima koji zadovoljavaju uvjete iz liste. Nad prethodno kreiranim nizom, pronađimo elemente koji su:
- manji od -1 i ako ih pronađemo podignimo ih na kvadrat
- manji od 2 i ako ih pronađemo podignimo ih na treću potenciju
- veći i jednaki od 2 te ako ih pronađemo podignimo ih na četvrtu potenciju.

**np.unique** je funkcija koja vraća **jedinstvene** elemente niza

Prije nego krenemo s naprednom primjenom NumPy biblioteke, upoznajmo se s još nekoliko funkcija vezanih uz nizove:
- *np.fliplr* - sortira redove obrnutim redoslijedom - *fliplr = Flip L(eft)R(ight)*
- *np.flipud* - sortira stupce obrnutim redoslijedom - *flipud = Flip U(p)D(own)*
- *np.sort* - sortira niz po zadanim osima
- *np.ndarray.sort* - sortira niz tako da ga modificira.

U sljedećem poglavlju ćemo se baviti analizom stvarnih podataka, u kojemu ćemo koristiti prethodno naučene biblioteke Pandas i matplotlib. matplotlib i Pandas su biblioteke razvijene na osnovi NumPy biblioteke te ćemo ih koristiti ovisno o njihovim najjačim stranama.

### Priča o najpoznatijoj matrici na svijetu - šahovskoj ploči

**Šah**

Najpoznatija matrica je ploča za jednu od najstarijih igara - šah. To je matrica 8x8.
Legenda o tome kako je igra dobila ime šah je jako zanimljiva. Šah (perzijski naziv za vladara) je gledao kako njegove sluge od putujućih trgovaca kupuju namirnice, tkaninu, začine i sl. Tako je ugledao dvojicu trgovaca kako igraju neku čudnu igru. Poslao je slugu da dovede trgovca koji je donio tu igru u njegovo kraljevstvo. Šah (vladar) je zatražio od trgovca da ga nauči igrati. Kada je naučio kako se igra, šah se toliko oduševio igrom da je odlučio bogato nagraditi trgovca. Rekao mu je neka kaže što želi kao nagradu za ovu igru. Trgovac je šahu, nakon što je naveo sve one slatkorječive riječi vladarima, kao što su Vaša visosti i sl., rekao:

*Želim pšenicu. Na prvo polje stavite jedno zrno pšenice. Na drugo dva zrna, na treće četiri, na četvrto dva puta više od prethodnog ... i tako do posljednjeg 64.-og polja.*

Šah se jako uvrijedio jer je očekivao da će trgovac tražiti zlato, drago kamenje, skupe začine pa ga je potjerao u vrt rekavši mu da će svoju vreću pšenice dobiti za ručak. Slugama je naredio neka ga isplate i to da nikada više ne želi vidjeti tog trgovca u njegovom kraljevstvu.

**PITANJE<br>
Koliko je trgovac trebao dobiti pšenice? Napišite program koji će to izračunati. Ako znate ovu priču, svejedno dozvolite drugim kolegama neka sami pokušaju doći do odgovora i svakako napišite program.**

Rezultat je: 18.446.744.073.709.551.616,00!<br>
Zna li netko pročitati ovaj broj?

Prošlo je nekoliko dana i šah je u vrtu vidio trgovca. Zvao je sluge i pitao što on još radi u njegovom kraljevstvu, odnosno zar nije isplaćen. Sluge su mu rekle da su njegovi matematičari izračunali:
- da svaki klas pšenice ima 40 zrna (četiri puta po 10 zrna - pogledajte sliku na internetu)
- da na jednom kvadratnom centimetru raste jedna stabljika pšenice s jednim klasom, na jednom kvadratnom metru ima 100 x 100 = 10.000,00 stabljika pšenica, dakle 400.000,00 zrna po kvadratnom metru
- da jedan kvadratni kilometar ima 1.000.000,00 kvadratnih metara pa na jednom kvadratnom kilometru ima 400.000.000.000,00 zrna pšenice.

Potrebno je posijati 46.116.860,18 (46 milijuna, 116 tisuća i 860,18) kvadratnih kilometara pšenicom da bi se trgovac isplatio. Usporedbe radi, ukupna površina kontinenta Azije je 44.580.000,00 kvadratnih kilometara.

Shvativši da ne može isplatiti trgovca, šah priđe trgovcu te mu se ispriča što je morao toliko čekati, ali se čekanje isplatilo. Pšenica je spremna za njegovu isplatu, ali šah ne bi volio da se trgovac osjeti prevarenim pa neka on sam izbroji svoju nagradu, a šahove sluge će biti uz njega i biti mu na usluzi dok on broji.

Trgovac je znao što ga čeka pa je odgovorio šahu da mu se zahvaljuje na nagradi, da mu nagrada sada nije važna te moli šaha da mu dozvoli da odmah krene kući jer je jutros dobio glas da mu je otac smrtno bolestan te bi se želio oprostiti od njega dok još može. Šah je dozvolio odlazak trgovca te mu dao dva konja puna namirnica potrebnih za put i još nešto zlatnika sa svrhom da požuri kući ocu, ali i da svijetom širi glas o milostivosti šaha.

*Napomena: legenda može odstupati od neke pisane verzije jer je ispričana po sjećanju.*